[[redirects]]
  from = "/admin-proxy/api/v1/*"
  to = "https://matp-admin.qchats.org/api/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/v1/*"
  to = "https://matp-app.qchats.org/api/v1/:splat"
  status = 200
  force = true
